apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
  labels:
    app: hello-world-app-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8010
