name: Deploy Hello World

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      - "v*-hello-world"
  pull_request:
    branches:
      - 'main'

jobs:
  deploy-docker-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - # create a build kit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the Docker build context
          file: ./Dockerfile  # Path to the Dockerfile
          push: false  # We won't push the image here, just tag it
          tags: avjpl/hello-world

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: avjpl/hello-world
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Print tagged images
        run: echo "${{ steps.metadata.outputs.tags }}"
#
#      - name: Login to image repository
#        if: github.ref_type == 'tag'
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GHCR_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: docker/dockerfile/hello-world/Dockerfile
#          push: ${{ github.ref_type == 'tag' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
