name: Deploy Hello World

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      - "v*-hello-world"
  pull_request:
    branches:
      - 'main'

jobs:
  deploy-docker-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: avjpl/hello-world
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - # create a build kit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the Docker build context
          file: ./Dockerfile  # Path to the Dockerfile
          push: false  # We won't push the image here, just tag it
          tags: avjpl/hello-world

      - name: Print tagged images
        run: |
          echo "${{ steps.metadata.outputs.tags }}"
          echo "${{ steps.metadata.outputs.labels }}"
          echo "actor: ${{ github.actor }}"
          echo "repository: ${{ github.repository }}"
          echo "repository_owner: ${{ github.repository_owner }}"
          echo "sha: ${{ github.sha }}"
